version: "3.9"
services:
  frontend:
    image: phippedersen/dockerized-frontend:latest
    container_name: frontend-container
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
